const categorizacionFields = [
  {
    type_element: "single-checkbox",
    id: "tipo_categorizacion",
    name: "tipo_categorizacion",
    label: "Tipo de Categorización",
    items_select: ["INTERNA", "EXTERNA"],
    default_value: () => "INTERNA",
  },
  {
    type_element: "text",
    id: "nombre",
    name: "nombre",
    label: "Nombre",
    cols_desktop: "md:basis-2/4",
    cols_mobile: "basis-full",
    show: false,
  },
  {
    type_element: "single-select",
    id: "empleado_id",
    name: "empleado_id",
    label: "Empleado",
    api_call: {
      method: "GET",
      endpoint: "api/list/empleadosActivos",
      params: null,
      headers: null,
    },
    cols_desktop: "md:basis-2/4",
    cols_mobile: "basis-full",
    show: false,
  },
  {
    type_element: "date",
    id: "fecha_evaluacion",
    name: "fecha_evaluacion",
    label: "Fecha de Evaluación",
    default_value: () => new Date().toString(),
  },
  {
    type_element: "single-select",
    id: "nivel_educacion_id",
    name: "nivel_educacion_id",
    label: "Nivel de Educación",
    cols_desktop: "md:basis-1/3",
    cols_mobile: "basis-full",
    api_call: {
      method: "GET",
      endpoint: "api/list/categorizacionEducacion",
      params: null,
      headers: null,
    },
    can_edit: false,
  },
  {
    type_element: "single-select",
    id: "nivel_formacion_id",
    name: "nivel_formacion_id",
    label: "Formación",
    cols_desktop: "md:basis-1/3",
    cols_mobile: "basis-full",
    api_call: {
      method: "GET",
      endpoint: "api/list/categorizacionFormacion",
      params: null,
      headers: null,
    },
    can_edit: false,
  },
  {
    type_element: "number",
    id: "years_experience",
    name: "years_experience",
    label: "Años de Experiencia",
    default_value: () => 0,
    min_value: 0,
    max_value: 100,
    accept_decimals: true,
  },
  {
    type_element: "single-select",
    id: "nivel_experiencia_id",
    name: "nivel_experiencia_id",
    label: "Experiencia",
    cols_desktop: "md:basis-1/3",
    cols_mobile: "basis-full",
    api_call: {
      method: "GET",
      endpoint: "api/list/categorizacionExperiencia",
      params: null,
      headers: null,
    },
    can_edit: false,
    disabled: true,
    // default_value: () => {
    //   return {
    //     id: 1,
    //     show_data: "Menos de 1 año - 10",
    //     calificacion: 10,
    //   };
    // },
  },
  {
    type_element: "number",
    id: "puntaje_obtenido",
    name: "puntaje_obtenido",
    label: "Puntaje Obtenido",
    default_value: () => 0,
    min_value: 0,
    max_value: 100,
    disabled: true,
  },
  {
    type_element: "single-select",
    id: "categoria_obtenida_id",
    name: "categoria_obtenida_id",
    label: "Categoría Obtenida",
    disabled: true,
  },
  {
    type_element: "price",
    id: "salario_segun_categorizacion",
    name: "salario_segun_categorizacion",
    label: "Salario Según Categorización",
    default_value: () => 0,
    disabled: true,
  },
  {
    type_element: "price",
    id: "salario_solicitado",
    name: "salario_solicitado",
    label: "Salario Solicitado",
    default_value: () => 0,
  },
  {
    type_element: "textarea",
    id: "observaciones",
    name: "observaciones",
    label: "Observaciones",
    cols_desktop: "md:basis-1/2",
    cols_mobile: "basis-full",
  },
];

export default categorizacionFields;
