const contratoFields = [
  {
    type_element: "single-select",
    id: "persona_id",
    name: "persona_id",
    label: "Persona",
    cols_desktop: "md:basis-2/4",
    cols_mobile: "basis-full",
    api_call: {
      method: "GET",
      endpoint: "api/list/personasSinContrato",
      params: null,
      headers: null,
    },
    can_edit: false,
  },
  {
    type_element: "single-checkbox",
    id: "tipo",
    name: "tipo",
    label: "Tipo de Contrato",
    items_select: [
      "INDEFINIDO",
      "FIJO",
    ],
  },
  {
    type_element: "single-checkbox",
    id: "modalidad",
    name: "modalidad",
    label: "Modalidad de Contrato",
    items_select: [
      "PRESENCIAL",
      "TELETRABAJO",
      "CONTRATISTA",
      "APRENDIZ",
      "PRACTICANTE",
    ],
  },
  {
    type_element: "date",
    id: "fecha_contratacion",
    name: "fecha_contratacion",
    label: "Fecha de Contratación",
  },
  {
    type_element: "date",
    id: "fecha_finalizacion",
    name: "fecha_finalizacion",
    label: "Fecha de Finalización",
    required: false,
  },
  {
    type_element: "single-select",
    id: "proceso_id",
    name: "proceso_id",
    label: "Proceso",
    api_call: {
      method: "GET",
      endpoint: "api/list/procesos",
      params: null,
      headers: null,
    },
    can_edit: false,
  },
  {
    type_element: "single-select",
    id: "area_id",
    name: "area_id",
    label: "Área",
    can_edit: false,
  },
  {
    type_element: "single-select",
    id: "cargo_id",
    name: "cargo_id",
    label: "Cargo",
  },
  {
    type_element: "single-select",
    id: "perfil_id",
    name: "perfil_id",
    label: "Perfil",
  },
  {
    type_element: "single-select",
    id: "empresa_id",
    name: "empresa_id",
    label: "Empresa",
    api_call: {
      method: "GET",
      endpoint: "api/list/empresas",
      params: null,
      headers: null,
    },
    can_edit: false,
  },
  {
    type_element: "single-checkbox",
    id: "tipo_afiliado",
    name: "tipo_afiliado",
    label: "Tipo de Afiliado",
    items_select: ["DEPENDIENTE", "INDEPENDIENTE"],
  },
  {
    type_element: "single-checkbox",
    id: "tipo_cotizante",
    name: "tipo_cotizante",
    label: "Tipo de Cotizante",
    items_select: ["DEPENDIENTE", "INDEPENDIENTE", "APRENDIZ"],
  },
  {
    type_element: "single-select",
    id: "eps_id",
    name: "eps_id",
    label: "EPS",
    api_call: {
      method: "GET",
      endpoint: "api/list/eps",
      params: null,
      headers: null,
    },
  },
  {
    type_element: "single-select",
    id: "afp_id",
    name: "afp_id",
    label: "AFP",
    api_call: {
      method: "GET",
      endpoint: "api/list/afp",
      params: null,
      headers: null,
    },
    required: false,
  },
  {
    type_element: "single-select",
    id: "arl_id",
    name: "arl_id",
    label: "ARL",
    api_call: {
      method: "GET",
      endpoint: "api/list/arl",
      params: null,
      headers: null,
    },
  },
  {
    type_element: "single-checkbox",
    id: "nivel_riesgo",
    name: "nivel_riesgo",
    label: "Nivel de Riesgo",
    items_select: ["NR1", "NR2", "NR3", "NR4", "NR5"],
  },
  {
    type_element: "single-select",
    id: "fondo_cesantia_id",
    name: "fondo_cesantia_id",
    label: "Fondo de Cesantía",
    api_call: {
      method: "GET",
      endpoint: "api/list/fondosCensantias",
      params: null,
      headers: null,
    },
    required: false,
  },
  {
    type_element: "single-select",
    id: "caja_compensacion_id",
    name: "caja_compensacion_id",
    label: "Caja de Compensación",
    api_call: {
      method: "GET",
      endpoint: "api/list/cajasCompensacion",
      params: null,
      headers: null,
    },
    required: false,
  },
  {
    type_element: "price",
    id: "salario",
    name: "salario",
    label: "Salario",
    default_value: () => 0,
  },
  {
    type_element: "number",
    id: "puntaje_expertiz",
    name: "puntaje_expertiz",
    label: "Puntaje Expertiz (0 - 100)",
    default_value: () => 0,
    min_value: 0,
    max_value: 100,
  },
  {
    type_element: "price",
    id: "dinero_no_constitutivo_salario",
    name: "dinero_no_constitutivo_salario",
    label: "No Constitutivo de Salario",
    default_value: () => 0,
    required: false,
  },
  {
    type_element: "number",
    id: "experiencia",
    name: "experiencia",
    label: "Experiencia (años)",
    default_value: () => 0.0,
    accept_decimals: true,
  },
  {
    type_element: "textarea",
    id: "observaciones",
    name: "observaciones",
    label: "Observaciones Novedad",
    cols_desktop: "md:basis-full",
    cols_mobile: "basis-full",
    show: false,
  },
];

export default contratoFields;
