const encuestaSatisfaccionFields = [
  {
    type_element: "text",
    id: "nombre_persona",
    name: "nombre_persona",
    label: "Nombre Completo",
    cols_desktop: "md:basis-full",
    cols_mobile: "basis-full",
  },
  {
    type_element: "single-checkbox",
    id: "motivos_compra",
    name: "motivos_compra",
    label: "Motivos de compra",
    items_select: [
      "Calidad en productos y servicios",
      "Reconocimiento",
      "Innovación",
      "Precio",
      "Confiabilidad y Cumplimiento",
      "Otros",
    ],
    cols_desktop: "md:basis-1/2",
    cols_mobile: "basis-full",
  },
  {
    type_element: "textarea",
    id: "observacion_motivos_compra",
    name: "observacion_motivos_compra",
    label: "Observaciones sobre los motivos de compra",
    cols_desktop: "md:basis-1/2",
    cols_mobile: "basis-full",
    required: false,
  },
  {
    type_element: "single-checkbox",
    id: "proceso_cotizacion",
    name: "proceso_cotizacion",
    label: "Proceso de cotización",
    items_select: [1, 2, 3, 4, 5],
    cols_desktop: "md:basis-1/2",
    cols_mobile: "basis-full",
  },
  {
    type_element: "textarea",
    id: "observacion_proceso_cotizacion",
    name: "observacion_proceso_cotizacion",
    label: "Observaciones sobre el proceso de cotización",
    cols_desktop: "md:basis-1/2",
    cols_mobile: "basis-full",
    required: false,
  },
  {
    type_element: "single-checkbox",
    id: "asesoria_y_acompanamiento",
    name: "asesoria_y_acompanamiento",
    label: "Asesoría y Acompañamiento",
    items_select: [1, 2, 3, 4, 5],
    cols_desktop: "md:basis-1/2",
    cols_mobile: "basis-full",
  },
  {
    type_element: "textarea",
    id: "observacion_asesoria_y_acompanamiento",
    name: "observacion_asesoria_y_acompanamiento",
    label: "Observaciones sobre la asesoría y acompañamiento",
    cols_desktop: "md:basis-1/2",
    cols_mobile: "basis-full",
    required: false,
  },
  {
    type_element: "single-checkbox",
    id: "cumplimiento_fecha_entrega",
    name: "cumplimiento_fecha_entrega",
    label: "Cumplimiento de la fecha de entrega",
    items_select: [1, 2, 3, 4, 5],
    cols_desktop: "md:basis-1/2",
    cols_mobile: "basis-full",
  },
  {
    type_element: "textarea",
    id: "observacion_cumplimiento_fecha_entrega",
    name: "observacion_cumplimiento_fecha_entrega",
    label: "Observaciones sobre el cumplimiento de la fecha de entrega",
    cols_desktop: "md:basis-1/2",
    cols_mobile: "basis-full",
    required: false,
  },
  {
    type_element: "single-checkbox",
    id: "informa_motivo_entrega",
    name: "informa_motivo_entrega",
    label: "Informa el motivo de la entrega",
    items_select: [1, 2, 3, 4, 5],
    cols_desktop: "md:basis-1/2",
    cols_mobile: "basis-full",
  },
  {
    type_element: "textarea",
    id: "observacion_informa_motivo_entrega",
    name: "observacion_informa_motivo_entrega",
    label: "Observaciones sobre la información del motivo de entrega",
    cols_desktop: "md:basis-1/2",
    cols_mobile: "basis-full",
    required: false,
  },
  {
    type_element: "single-checkbox",
    id: "calidad_servicios",
    name: "calidad_servicios",
    label: "Calidad de los servicios",
    items_select: [1, 2, 3, 4, 5],
    cols_desktop: "md:basis-1/2",
    cols_mobile: "basis-full",
  },
  {
    type_element: "textarea",
    id: "observacion_calidad_servicios",
    name: "observacion_calidad_servicios",
    label: "Observaciones sobre la calidad de los servicios",
    cols_desktop: "md:basis-1/2",
    cols_mobile: "basis-full",
    required: false,
  },
  {
    type_element: "single-checkbox",
    id: "respuesta_a_reclamos",
    name: "respuesta_a_reclamos",
    label: "Respuesta a reclamos",
    items_select: [1, 2, 3, 4, 5],
    cols_desktop: "md:basis-1/2",
    cols_mobile: "basis-full",
  },
  {
    type_element: "textarea",
    id: "observacion_respuesta_a_reclamos",
    name: "observacion_respuesta_a_reclamos",
    label: "Observaciones sobre la respuesta a reclamos",
    cols_desktop: "md:basis-1/2",
    cols_mobile: "basis-full",
    required: false,
  },
  {
    type_element: "single-checkbox",
    id: "percepcion_calidad",
    name: "percepcion_calidad",
    label: "Percepción de calidad",
    items_select: [1, 2, 3, 4, 5],
    cols_desktop: "md:basis-1/2",
    cols_mobile: "basis-full",
  },
  {
    type_element: "textarea",
    id: "observacion_percepcion_calidad",
    name: "observacion_percepcion_calidad",
    label: "Observaciones sobre la percepción de calidad",
    cols_desktop: "md:basis-1/2",
    cols_mobile: "basis-full",
    required: false,
  },
  {
    type_element: "single-checkbox",
    id: "capacidad_tecnica",
    name: "capacidad_tecnica",
    label: "Capacidad técnica",
    items_select: [1, 2, 3, 4, 5],
    cols_desktop: "md:basis-1/2",
    cols_mobile: "basis-full",
  },
  {
    type_element: "textarea",
    id: "observacion_capacidad_tecnica",
    name: "observacion_capacidad_tecnica",
    label: "Observaciones sobre la capacidad técnica",
    cols_desktop: "md:basis-1/2",
    cols_mobile: "basis-full",
    required: false,
  },
  {
    type_element: "single-checkbox",
    id: "opinion_solicitudes_obra",
    name: "opinion_solicitudes_obra",
    label: "Opinión sobre las solicitudes de obra",
    items_select: [1, 2, 3, 4, 5],
    cols_desktop: "md:basis-1/2",
    cols_mobile: "basis-full",
  },
  {
    type_element: "textarea",
    id: "observacion_opinion_solicitudes_obra",
    name: "observacion_opinion_solicitudes_obra",
    label: "Observaciones sobre las solicitudes de obra",
    cols_desktop: "md:basis-1/2",
    cols_mobile: "basis-full",
    required: false,
  },
  {
    type_element: "single-checkbox",
    id: "opinion_tiempo_respuesta_preguntas",
    name: "opinion_tiempo_respuesta_preguntas",
    label: "Opinión sobre el tiempo de respuesta a preguntas",
    items_select: [1, 2, 3, 4, 5],
    cols_desktop: "md:basis-1/2",
    cols_mobile: "basis-full",
  },
  {
    type_element: "textarea",
    id: "observacion_opinion_tiempo_respuesta_preguntas",
    name: "observacion_opinion_tiempo_respuesta_preguntas",
    label: "Observaciones sobre el tiempo de respuesta a preguntas",
    cols_desktop: "md:basis-1/2",
    cols_mobile: "basis-full",
    required: false,
  },
  {
    type_element: "textarea",
    id: "observacion_organizacion_empresarial",
    name: "observacion_organizacion_empresarial",
    label: "Observaciones sobre la organización empresarial",
    cols_desktop: "md:basis-1/2",
    cols_mobile: "basis-full",
    required: true,
  },
  {
    type_element: "textarea",
    id: "observacion_sugerencias_mejora",
    name: "observacion_sugerencias_mejora",
    label: "Observaciones y Sugerencias de Mejora",
    cols_desktop: "md:basis-1/2",
    cols_mobile: "basis-full",
    required: true,
  },
];

export default encuestaSatisfaccionFields;
