const informacionBasicaFields = [
  {
    type_element: "text",
    id: "nombre_completo",
    name: "nombre_completo",
    label: "Nombre Completo",
    cols_desktop: "md:basis-1/2",
    cols_mobile: "basis-full",
    can_edit: false,
  },
  {
    type_element: "single-checkbox",
    id: "genero",
    name: "genero",
    label: "Género",
    items_select: ["Masculino", "Femenino", "Otro"],
    can_edit: false,
  },
  {
    type_element: "date",
    id: "fecha_nacimiento",
    name: "fecha_nacimiento",
    label: "Fecha de Nacimiento",
    can_edit: false,
  },
  {
    type_element: "single-select",
    id: "pais_nacimiento_id",
    name: "pais_nacimiento_id",
    label: "País de Nacimiento",
    api_call: {
      method: "GET",
      endpoint: "api/list/paises",
      params: null,
      headers: null,
    },
    can_edit: false,
  },
  {
    type_element: "single-select",
    id: "departamento_nacimiento_id",
    name: "departamento_nacimiento_id",
    label: "Dpto. de Nacimiento",
    required: false,
    can_edit: false,
  },
  {
    type_element: "single-select",
    id: "municipio_nacimiento_id",
    name: "municipio_nacimiento_id",
    label: "Mncipio. de Nacimiento",
    required: false,
    can_edit: false,
  },
  {
    type_element: "single-checkbox",
    id: "tipo_documento",
    name: "tipo_documento",
    label: "Tipo Documento",
    items_select: ["CC", "NIT"],
    cols_desktop: "md:basis-1/4",
    cols_mobile: "basis-full",
    can_edit: false,
  },
  {
    type_element: "number",
    id: "nro_documento",
    name: "nro_documento",
    label: "N° Documento",
    cols_desktop: "md:basis-1/4",
    cols_mobile: "basis-full",
    can_edit: false,
  },
  {
    type_element: "single-select",
    id: "pais_expedicion_id",
    name: "pais_expedicion_id",
    label: "País de Expedición",
    api_call: {
      method: "GET",
      endpoint: "api/list/paises",
      params: null,
      headers: null,
    },
    can_edit: false,
  },
  {
    type_element: "single-select",
    id: "departamento_expedicion_id",
    name: "departamento_expedicion_id",
    label: "Dpto. de Expedición",
    required: false,
    can_edit: false,
  },
  {
    type_element: "single-select",
    id: "municipio_expedicion_id",
    name: "municipio_expedicion_id",
    label: "Mncipio. de Expedición",
    required: false,
    can_edit: false,
  },
];

export default informacionBasicaFields;
