const informacionLaboralFields = [
  {
    type_element: "single-checkbox",
    id: "tipo",
    name: "tipo",
    label: "Tipo de Contrato",
    items_select: [
      "INDEFINIDO",
      "FIJO",
      "TELETRABAJO",
      "CONTRATISTA",
      "APRENDIZ",
      "PRACTICANTE",
    ],
    can_edit: false,
  },

  {
    type_element: "date",
    id: "fecha_contratacion",
    name: "fecha_contratacion",
    label: "Fecha de Contratación",
    can_edit: false,
  },
  {
    type_element: "date",
    id: "fecha_finalizacion",
    name: "fecha_finalizacion",
    label: "Fecha de Finalización",
    required: false,
    can_edit: false,
  },
  {
    type_element: "single-select",
    id: "proceso_id",
    name: "proceso_id",
    label: "Proceso",
    can_edit: false,
  },
  {
    type_element: "single-select",
    id: "area_id",
    name: "area_id",
    label: "Área",
    can_edit: false,
  },
  {
    type_element: "single-select",
    id: "cargo_id",
    name: "cargo_id",
    label: "Cargo",
    can_edit: false,
  },
  {
    type_element: "single-select",
    id: "perfil_id",
    name: "perfil_id",
    label: "Perfil",
    can_edit: false,
  },
  {
    type_element: "single-select",
    id: "empresa_id",
    name: "empresa_id",
    label: "Empresa",
    can_edit: false,
  },
  {
    type_element: "price",
    id: "salario",
    name: "salario",
    label: "Salario",
    default_value: () => 0,
    can_edit: false,
  },
  {
    type_element: "number",
    id: "puntaje_expertiz",
    name: "puntaje_expertiz",
    label: "Puntaje Expertiz",
    default_value: () => 0,
    can_edit: false,
  },
  {
    type_element: "price",
    id: "dinero_no_constitutivo_salario",
    name: "dinero_no_constitutivo_salario",
    label: "No Constitutivo de Salario",
    default_value: () => 0,
    required: false,
    can_edit: false,
  },
  {
    type_element: "number",
    id: "experiencia",
    name: "experiencia",
    label: "Experiencia",
    default_value: () => 0,
    can_edit: false,
  },
];

export default informacionLaboralFields;
