const ordenTrabajoFields = [
  {
    type_element: "single-select",
    id: "servicio_id",
    name: "servicio_id",
    label: "Servicio",
    cols_desktop: "md:basis-1/2",
    cols_mobile: "basis-full",
    api_call: {
      method: "GET",
      endpoint: "api/list/servicios",
      params: null,
      headers: null,
    },
    can_edit: false,
  },
  {
    type_element: "single-select",
    id: "coordinador_ingenieria_junior_id",
    name: "coordinador_ingenieria_junior_id",
    label: "Coordinador Ingeniería Junior",
    cols_desktop: "md:basis-1/2",
    cols_mobile: "basis-full",
    api_call: {
      method: "GET",
      endpoint: "api/list/personas",
      params: null,
      headers: null,
    },
    can_edit: false,
  },
  {
    type_element: "single-select",
    id: "coordinador_dibujo_junior_id",
    name: "coordinador_dibujo_junior_id",
    label: "Coordinador Dibujo Junior",
    cols_desktop: "md:basis-1/2",
    cols_mobile: "basis-full",
    api_call: {
      method: "GET",
      endpoint: "api/list/personas",
      params: null,
      headers: null,
    },
    can_edit: false,
  },
  {
    type_element: "tag",
    id: "etapas",
    name: "etapas",
    label: "Etapas",
    cols_desktop: "md:basis-full",
    cols_mobile: "basis-full",
    api_call: {
      method: "GET",
      endpoint: "api/list/etapas",
      params: null,
      headers: null,
    },
    can_add: true,
    can_edit: false,
    select_all: true,
  },
  {
    type_element: "single-checkbox",
    id: "reproceso_externo",
    name: "reproceso_externo",
    label: "Reproceso Externo",
    items_select: ["SI", "NO"],
  },
  {
    type_element: "single-checkbox",
    id: "cantidades_obra",
    name: "cantidades_obra",
    label: "Cantidades de Obra",
    items_select: ["SI", "NO"],
  },
  {
    type_element: "textarea",
    id: "descripcion",
    name: "descripcion",
    label: "Descripción",
    cols_desktop: "md:basis-2/4",
    cols_mobile: "basis-full",
  },
];

export default ordenTrabajoFields;
