const personaFields = [
  {
    type_element: "text",
    id: "primer_nombre",
    name: "primer_nombre",
    label: "Primer Nombre",
    cols_desktop: "md:basis-1/4",
    cols_mobile: "basis-full",
  },
  {
    type_element: "text",
    id: "segundo_nombre",
    name: "segundo_nombre",
    label: "Segundo Nombre",
    cols_desktop: "md:basis-1/4",
    cols_mobile: "basis-full",
    required: false,
  },
  {
    type_element: "text",
    id: "primer_apellido",
    name: "primer_apellido",
    label: "Primer Apellido",
    cols_desktop: "md:basis-1/4",
    cols_mobile: "basis-full",
  },
  {
    type_element: "text",
    id: "segundo_apellido",
    name: "segundo_apellido",
    label: "Segundo Apellido",
    cols_desktop: "md:basis-1/4",
    cols_mobile: "basis-full",
  },
  {
    type_element: "single-checkbox",
    id: "genero",
    name: "genero",
    label: "Género",
    items_select: ["Masculino", "Femenino", "Otro"],
  },
  {
    type_element: "date",
    id: "fecha_nacimiento",
    name: "fecha_nacimiento",
    label: "Fecha de Nacimiento",
  },
  {
    type_element: "single-select",
    id: "pais_nacimiento_id",
    name: "pais_nacimiento_id",
    label: "País de Nacimiento",
    api_call: {
      method: "GET",
      endpoint: "api/list/paises",
      params: null,
      headers: null,
    },
  },
  {
    type_element: "single-select",
    id: "departamento_nacimiento_id",
    name: "departamento_nacimiento_id",
    label: "Dpto. de Nacimiento",
    required: false,
  },
  {
    type_element: "single-select",
    id: "municipio_nacimiento_id",
    name: "municipio_nacimiento_id",
    label: "Mncipio. de Nacimiento",
    required: false,
  },
  {
    type_element: "single-checkbox",
    id: "tipo_documento",
    name: "tipo_documento",
    label: "Tipo Documento",
    items_select: ["CC", "NIT", "TI", "CE"],
    cols_desktop: "md:basis-1/4",
    cols_mobile: "basis-full",
  },
  {
    type_element: "number",
    id: "nro_documento",
    name: "nro_documento",
    label: "N° Documento",
    cols_desktop: "md:basis-1/4",
    cols_mobile: "basis-full",
  },
  {
    type_element: "single-select",
    id: "pais_expedicion_id",
    name: "pais_expedicion_id",
    label: "País de Expedición",
    api_call: {
      method: "GET",
      endpoint: "api/list/paises",
      params: null,
      headers: null,
    },
  },
  {
    type_element: "single-select",
    id: "departamento_expedicion_id",
    name: "departamento_expedicion_id",
    label: "Dpto. de Expedición",
    required: false,
  },
  {
    type_element: "single-select",
    id: "municipio_expedicion_id",
    name: "municipio_expedicion_id",
    label: "Mncipio. de Expedición",
    required: false,
  },
  {
    type_element: "text",
    id: "direccion_domicilio",
    name: "direccion_domicilio",
    label: "Dirección de Domicilio",
    cols_desktop: "md:basis-2/4",
    cols_mobile: "basis-full",
  },
  {
    type_element: "single-select",
    id: "pais_domicilio_id",
    name: "pais_domicilio_id",
    label: "País de Domicilio",
    api_call: {
      method: "GET",
      endpoint: "api/list/paises",
      params: null,
      headers: null,
    },
  },
  {
    type_element: "single-select",
    id: "departamento_domicilio_id",
    name: "departamento_domicilio_id",
    label: "Dpto. de Domicilio",
    required: false,
  },
  {
    type_element: "single-select",
    id: "municipio_domicilio_id",
    name: "municipio_domicilio_id",
    label: "Mncipio. de Domicilio",
    required: false,
  },
  {
    type_element: "text",
    id: "telefono_celular",
    name: "telefono_celular",
    label: "Teléfono Celular",
  },
  {
    type_element: "email",
    id: "email",
    name: "email",
    label: "Correo Electrónico Personal",
    cols_desktop: "md:basis-2/4",
    cols_mobile: "basis-full",
  },
];

export default personaFields;
