const socioEconomicoFields = [
  {
    type_element: "single-select",
    id: "nivel_academico_id",
    name: "nivel_academico_id",
    label: "Nivel Académico",
    api_call: {
      method: "GET",
      endpoint: "api/list/nivelesAcademicos",
      params: null,
      headers: null,
    },
  },
  {
    type_element: "single-checkbox",
    id: "estado_civil",
    name: "estado_civil",
    label: "Estado Civil",
    items_select: ["Soltero", "Casado", "Unión Libre", "Separado", "Viudo"],
  },
  {
    type_element: "single-checkbox",
    id: "cabeza_familia",
    name: "cabeza_familia",
    label: "¿Es cabeza de familia?",
    items_select: ["SI", "NO"],
  },
  {
    type_element: "number",
    id: "nro_hijos",
    name: "nro_hijos",
    label: "N° de Hijos",
  },
  {
    type_element: "number",
    id: "nro_persona_hogar",
    name: "nro_persona_hogar",
    label: "N° de Personas en el Hogar",
  },
  {
    type_element: "number",
    id: "nro_persona_discapacidad",
    name: "nro_persona_discapacidad",
    label: "N° de Personas con Discapacidad",
  },
  {
    type_element: "single-checkbox",
    id: "ingresos_familiares_mensuales",
    name: "ingresos_familiares_mensuales",
    label: "Ingresos Familiares Mensuales",
    items_select: [
      "Menos de un SMMLV",
      "Entre 1 y 2 SMMLV",
      "Entre 2 y 3 SMMLV",
      "Entre 3 y 4 SMMLV",
      "Entre 4 y 5 SMMLV",
      "Más de 5 SMMLV",
    ],
  },
  {
    type_element: "single-checkbox",
    id: "solvencia_economica",
    name: "solvencia_economica",
    label: "Solvencia Económica",
    items_select: ["SI", "NO"],
  },
  {
    type_element: "single-checkbox",
    id: "tipo_transporte",
    name: "tipo_transporte",
    label: "Tipo de Transporte",
    items_select: [
      "Caminando",
      "Bicicleta",
      "Moto",
      "Vehículo particular",
      "Transporte público",
    ],
  },
  {
    type_element: "single-checkbox",
    id: "tipo_vivienda",
    name: "tipo_vivienda",
    label: "Tipo de Vivienda",
    items_select: ["CASA", "APARTAMENTO"],
  },
  {
    type_element: "single-checkbox",
    id: "caracteristicas_vivienda",
    name: "caracteristicas_vivienda",
    label: "Características de la Vivienda",
    items_select: ["ARRENDADA", "PROPIA", "FAMILIAR"],
  },
  {
    type_element: "single-checkbox",
    id: "zona_vivienda",
    name: "zona_vivienda",
    label: "Zona de Vivienda",
    items_select: ["RURAL", "URBANA"],
  },
  {
    type_element: "single-checkbox",
    id: "estrato_vivienda",
    name: "estrato_vivienda",
    label: "Estrato de Vivienda",
    items_select: ["1", "2", "3", "4", "5", "6"],
  },
  {
    type_element: "single-checkbox",
    id: "energia_electrica",
    name: "energia_electrica",
    label: "¿Tiene Energía Eléctrica?",
    items_select: ["SI", "NO"],
  },
  {
    type_element: "single-checkbox",
    id: "alcantarillado",
    name: "alcantarillado",
    label: "¿Tiene Alcantarillado?",
    items_select: ["SI", "NO"],
  },
  {
    type_element: "single-checkbox",
    id: "acueducto",
    name: "acueducto",
    label: "¿Tiene Acueducto?",
    items_select: ["SI", "NO"],
  },
  {
    type_element: "single-checkbox",
    id: "gas_natural",
    name: "gas_natural",
    label: "¿Tiene Gas Natural?",
    items_select: ["SI", "NO"],
  },
  {
    type_element: "single-checkbox",
    id: "aseo_publico",
    name: "aseo_publico",
    label: "¿Tiene Aseo Público?",
    items_select: ["SI", "NO"],
  },
  {
    type_element: "single-checkbox",
    id: "tiene_telefono_fijo",
    name: "tiene_telefono_fijo",
    label: "¿Tiene Teléfono Fijo?",
    items_select: ["SI", "NO"],
  },
  {
    type_element: "single-checkbox",
    id: "internet",
    name: "internet",
    label: "¿Tiene Internet?",
    items_select: ["SI", "NO"],
  },
  {
    type_element: "single-checkbox",
    id: "computador",
    name: "computador",
    label: "¿Tiene Computador?",
    items_select: ["SI", "NO"],
  },
  {
    type_element: "single-checkbox",
    id: "deudas",
    name: "deudas",
    label: "¿Tiene Deudas?",
    items_select: ["SI", "NO"],
  },
  {
    type_element: "single-checkbox",
    id: "interesado_refinanciamiento",
    name: "interesado_refinanciamiento",
    label: "¿Está Interesado en Refinanciamiento?",
    items_select: ["SI", "NO"],
  },
];
export default socioEconomicoFields;
